"""add_job_dependencies

Revision ID: d61bb613fd83
Revises: 99d3c25dbacc
Create Date: 2026-03-06 03:27:02.613484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61bb613fd83'
down_revision = '99d3c25dbacc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_jobs', sa.Column('before_job_id', sa.UUID(), nullable=True))
    op.add_column('scheduler_jobs', sa.Column('after_job_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_jobs', 'after_job_id')
    op.drop_column('scheduler_jobs', 'before_job_id')
    # ### end Alembic commands ###
